/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthUsersIndexRouteImport } from './routes/_auth/users/index'
import { Route as AuthTagsIndexRouteImport } from './routes/_auth/tags/index'
import { Route as AuthReviewsIndexRouteImport } from './routes/_auth/reviews/index'
import { Route as AuthNewsletterIndexRouteImport } from './routes/_auth/newsletter/index'
import { Route as AuthMediaIndexRouteImport } from './routes/_auth/media/index'
import { Route as AuthInquiriesIndexRouteImport } from './routes/_auth/inquiries/index'
import { Route as AuthDestinationsIndexRouteImport } from './routes/_auth/destinations/index'
import { Route as AuthDeparturesIndexRouteImport } from './routes/_auth/departures/index'
import { Route as AuthDashboardIndexRouteImport } from './routes/_auth/dashboard/index'
import { Route as AuthBookingsIndexRouteImport } from './routes/_auth/bookings/index'
import { Route as AuthBlogsIndexRouteImport } from './routes/_auth/blogs/index'
import { Route as AuthAuthorsIndexRouteImport } from './routes/_auth/authors/index'
import { Route as AuthTagsCreateRouteImport } from './routes/_auth/tags/create'
import { Route as AuthSettingsNavbarRouteImport } from './routes/_auth/settings/navbar'
import { Route as AuthSettingsLandingPageRouteImport } from './routes/_auth/settings/landing-page'
import { Route as AuthInquiriesIdRouteImport } from './routes/_auth/inquiries/$id'
import { Route as AuthDestinationsCreateRouteImport } from './routes/_auth/destinations/create'
import { Route as AuthDeparturesCreateRouteImport } from './routes/_auth/departures/create'
import { Route as AuthBookingsIdRouteImport } from './routes/_auth/bookings/$id'
import { Route as AuthBlogsCreateRouteImport } from './routes/_auth/blogs/create'
import { Route as AuthAuthorsCreateRouteImport } from './routes/_auth/authors/create'
import { Route as AuthTagsEditIdRouteImport } from './routes/_auth/tags/edit/$id'
import { Route as AuthDestinationsEditIdRouteImport } from './routes/_auth/destinations/edit/$id'
import { Route as AuthDeparturesEditIdRouteImport } from './routes/_auth/departures/edit/$id'
import { Route as AuthBlogsEditIdRouteImport } from './routes/_auth/blogs/edit/$id'
import { Route as AuthAuthorsEditIdRouteImport } from './routes/_auth/authors/edit/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthUsersIndexRoute = AuthUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagsIndexRoute = AuthTagsIndexRouteImport.update({
  id: '/tags/',
  path: '/tags/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReviewsIndexRoute = AuthReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNewsletterIndexRoute = AuthNewsletterIndexRouteImport.update({
  id: '/newsletter/',
  path: '/newsletter/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthMediaIndexRoute = AuthMediaIndexRouteImport.update({
  id: '/media/',
  path: '/media/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInquiriesIndexRoute = AuthInquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDestinationsIndexRoute = AuthDestinationsIndexRouteImport.update({
  id: '/destinations/',
  path: '/destinations/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeparturesIndexRoute = AuthDeparturesIndexRouteImport.update({
  id: '/departures/',
  path: '/departures/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardIndexRoute = AuthDashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBookingsIndexRoute = AuthBookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBlogsIndexRoute = AuthBlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthorsIndexRoute = AuthAuthorsIndexRouteImport.update({
  id: '/authors/',
  path: '/authors/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagsCreateRoute = AuthTagsCreateRouteImport.update({
  id: '/tags/create',
  path: '/tags/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsNavbarRoute = AuthSettingsNavbarRouteImport.update({
  id: '/settings/navbar',
  path: '/settings/navbar',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSettingsLandingPageRoute = AuthSettingsLandingPageRouteImport.update({
  id: '/settings/landing-page',
  path: '/settings/landing-page',
  getParentRoute: () => AuthRoute,
} as any)
const AuthInquiriesIdRoute = AuthInquiriesIdRouteImport.update({
  id: '/inquiries/$id',
  path: '/inquiries/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDestinationsCreateRoute = AuthDestinationsCreateRouteImport.update({
  id: '/destinations/create',
  path: '/destinations/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeparturesCreateRoute = AuthDeparturesCreateRouteImport.update({
  id: '/departures/create',
  path: '/departures/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBookingsIdRoute = AuthBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBlogsCreateRoute = AuthBlogsCreateRouteImport.update({
  id: '/blogs/create',
  path: '/blogs/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthorsCreateRoute = AuthAuthorsCreateRouteImport.update({
  id: '/authors/create',
  path: '/authors/create',
  getParentRoute: () => AuthRoute,
} as any)
const AuthTagsEditIdRoute = AuthTagsEditIdRouteImport.update({
  id: '/tags/edit/$id',
  path: '/tags/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDestinationsEditIdRoute = AuthDestinationsEditIdRouteImport.update({
  id: '/destinations/edit/$id',
  path: '/destinations/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDeparturesEditIdRoute = AuthDeparturesEditIdRouteImport.update({
  id: '/departures/edit/$id',
  path: '/departures/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBlogsEditIdRoute = AuthBlogsEditIdRouteImport.update({
  id: '/blogs/edit/$id',
  path: '/blogs/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAuthorsEditIdRoute = AuthAuthorsEditIdRouteImport.update({
  id: '/authors/edit/$id',
  path: '/authors/edit/$id',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/authors/create': typeof AuthAuthorsCreateRoute
  '/blogs/create': typeof AuthBlogsCreateRoute
  '/bookings/$id': typeof AuthBookingsIdRoute
  '/departures/create': typeof AuthDeparturesCreateRoute
  '/destinations/create': typeof AuthDestinationsCreateRoute
  '/inquiries/$id': typeof AuthInquiriesIdRoute
  '/settings/landing-page': typeof AuthSettingsLandingPageRoute
  '/settings/navbar': typeof AuthSettingsNavbarRoute
  '/tags/create': typeof AuthTagsCreateRoute
  '/authors/': typeof AuthAuthorsIndexRoute
  '/blogs/': typeof AuthBlogsIndexRoute
  '/bookings/': typeof AuthBookingsIndexRoute
  '/dashboard/': typeof AuthDashboardIndexRoute
  '/departures/': typeof AuthDeparturesIndexRoute
  '/destinations/': typeof AuthDestinationsIndexRoute
  '/inquiries/': typeof AuthInquiriesIndexRoute
  '/media/': typeof AuthMediaIndexRoute
  '/newsletter/': typeof AuthNewsletterIndexRoute
  '/reviews/': typeof AuthReviewsIndexRoute
  '/tags/': typeof AuthTagsIndexRoute
  '/users/': typeof AuthUsersIndexRoute
  '/authors/edit/$id': typeof AuthAuthorsEditIdRoute
  '/blogs/edit/$id': typeof AuthBlogsEditIdRoute
  '/departures/edit/$id': typeof AuthDeparturesEditIdRoute
  '/destinations/edit/$id': typeof AuthDestinationsEditIdRoute
  '/tags/edit/$id': typeof AuthTagsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof AuthProfileRoute
  '/authors/create': typeof AuthAuthorsCreateRoute
  '/blogs/create': typeof AuthBlogsCreateRoute
  '/bookings/$id': typeof AuthBookingsIdRoute
  '/departures/create': typeof AuthDeparturesCreateRoute
  '/destinations/create': typeof AuthDestinationsCreateRoute
  '/inquiries/$id': typeof AuthInquiriesIdRoute
  '/settings/landing-page': typeof AuthSettingsLandingPageRoute
  '/settings/navbar': typeof AuthSettingsNavbarRoute
  '/tags/create': typeof AuthTagsCreateRoute
  '/authors': typeof AuthAuthorsIndexRoute
  '/blogs': typeof AuthBlogsIndexRoute
  '/bookings': typeof AuthBookingsIndexRoute
  '/dashboard': typeof AuthDashboardIndexRoute
  '/departures': typeof AuthDeparturesIndexRoute
  '/destinations': typeof AuthDestinationsIndexRoute
  '/inquiries': typeof AuthInquiriesIndexRoute
  '/media': typeof AuthMediaIndexRoute
  '/newsletter': typeof AuthNewsletterIndexRoute
  '/reviews': typeof AuthReviewsIndexRoute
  '/tags': typeof AuthTagsIndexRoute
  '/users': typeof AuthUsersIndexRoute
  '/authors/edit/$id': typeof AuthAuthorsEditIdRoute
  '/blogs/edit/$id': typeof AuthBlogsEditIdRoute
  '/departures/edit/$id': typeof AuthDeparturesEditIdRoute
  '/destinations/edit/$id': typeof AuthDestinationsEditIdRoute
  '/tags/edit/$id': typeof AuthTagsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/authors/create': typeof AuthAuthorsCreateRoute
  '/_auth/blogs/create': typeof AuthBlogsCreateRoute
  '/_auth/bookings/$id': typeof AuthBookingsIdRoute
  '/_auth/departures/create': typeof AuthDeparturesCreateRoute
  '/_auth/destinations/create': typeof AuthDestinationsCreateRoute
  '/_auth/inquiries/$id': typeof AuthInquiriesIdRoute
  '/_auth/settings/landing-page': typeof AuthSettingsLandingPageRoute
  '/_auth/settings/navbar': typeof AuthSettingsNavbarRoute
  '/_auth/tags/create': typeof AuthTagsCreateRoute
  '/_auth/authors/': typeof AuthAuthorsIndexRoute
  '/_auth/blogs/': typeof AuthBlogsIndexRoute
  '/_auth/bookings/': typeof AuthBookingsIndexRoute
  '/_auth/dashboard/': typeof AuthDashboardIndexRoute
  '/_auth/departures/': typeof AuthDeparturesIndexRoute
  '/_auth/destinations/': typeof AuthDestinationsIndexRoute
  '/_auth/inquiries/': typeof AuthInquiriesIndexRoute
  '/_auth/media/': typeof AuthMediaIndexRoute
  '/_auth/newsletter/': typeof AuthNewsletterIndexRoute
  '/_auth/reviews/': typeof AuthReviewsIndexRoute
  '/_auth/tags/': typeof AuthTagsIndexRoute
  '/_auth/users/': typeof AuthUsersIndexRoute
  '/_auth/authors/edit/$id': typeof AuthAuthorsEditIdRoute
  '/_auth/blogs/edit/$id': typeof AuthBlogsEditIdRoute
  '/_auth/departures/edit/$id': typeof AuthDeparturesEditIdRoute
  '/_auth/destinations/edit/$id': typeof AuthDestinationsEditIdRoute
  '/_auth/tags/edit/$id': typeof AuthTagsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/authors/create'
    | '/blogs/create'
    | '/bookings/$id'
    | '/departures/create'
    | '/destinations/create'
    | '/inquiries/$id'
    | '/settings/landing-page'
    | '/settings/navbar'
    | '/tags/create'
    | '/authors/'
    | '/blogs/'
    | '/bookings/'
    | '/dashboard/'
    | '/departures/'
    | '/destinations/'
    | '/inquiries/'
    | '/media/'
    | '/newsletter/'
    | '/reviews/'
    | '/tags/'
    | '/users/'
    | '/authors/edit/$id'
    | '/blogs/edit/$id'
    | '/departures/edit/$id'
    | '/destinations/edit/$id'
    | '/tags/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/authors/create'
    | '/blogs/create'
    | '/bookings/$id'
    | '/departures/create'
    | '/destinations/create'
    | '/inquiries/$id'
    | '/settings/landing-page'
    | '/settings/navbar'
    | '/tags/create'
    | '/authors'
    | '/blogs'
    | '/bookings'
    | '/dashboard'
    | '/departures'
    | '/destinations'
    | '/inquiries'
    | '/media'
    | '/newsletter'
    | '/reviews'
    | '/tags'
    | '/users'
    | '/authors/edit/$id'
    | '/blogs/edit/$id'
    | '/departures/edit/$id'
    | '/destinations/edit/$id'
    | '/tags/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/login'
    | '/_auth/profile'
    | '/_auth/authors/create'
    | '/_auth/blogs/create'
    | '/_auth/bookings/$id'
    | '/_auth/departures/create'
    | '/_auth/destinations/create'
    | '/_auth/inquiries/$id'
    | '/_auth/settings/landing-page'
    | '/_auth/settings/navbar'
    | '/_auth/tags/create'
    | '/_auth/authors/'
    | '/_auth/blogs/'
    | '/_auth/bookings/'
    | '/_auth/dashboard/'
    | '/_auth/departures/'
    | '/_auth/destinations/'
    | '/_auth/inquiries/'
    | '/_auth/media/'
    | '/_auth/newsletter/'
    | '/_auth/reviews/'
    | '/_auth/tags/'
    | '/_auth/users/'
    | '/_auth/authors/edit/$id'
    | '/_auth/blogs/edit/$id'
    | '/_auth/departures/edit/$id'
    | '/_auth/destinations/edit/$id'
    | '/_auth/tags/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/users/': {
      id: '/_auth/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthUsersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tags/': {
      id: '/_auth/tags/'
      path: '/tags'
      fullPath: '/tags/'
      preLoaderRoute: typeof AuthTagsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reviews/': {
      id: '/_auth/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthReviewsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/newsletter/': {
      id: '/_auth/newsletter/'
      path: '/newsletter'
      fullPath: '/newsletter/'
      preLoaderRoute: typeof AuthNewsletterIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/media/': {
      id: '/_auth/media/'
      path: '/media'
      fullPath: '/media/'
      preLoaderRoute: typeof AuthMediaIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inquiries/': {
      id: '/_auth/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof AuthInquiriesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/destinations/': {
      id: '/_auth/destinations/'
      path: '/destinations'
      fullPath: '/destinations/'
      preLoaderRoute: typeof AuthDestinationsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departures/': {
      id: '/_auth/departures/'
      path: '/departures'
      fullPath: '/departures/'
      preLoaderRoute: typeof AuthDeparturesIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard/': {
      id: '/_auth/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthDashboardIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bookings/': {
      id: '/_auth/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthBookingsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/blogs/': {
      id: '/_auth/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof AuthBlogsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/authors/': {
      id: '/_auth/authors/'
      path: '/authors'
      fullPath: '/authors/'
      preLoaderRoute: typeof AuthAuthorsIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tags/create': {
      id: '/_auth/tags/create'
      path: '/tags/create'
      fullPath: '/tags/create'
      preLoaderRoute: typeof AuthTagsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/navbar': {
      id: '/_auth/settings/navbar'
      path: '/settings/navbar'
      fullPath: '/settings/navbar'
      preLoaderRoute: typeof AuthSettingsNavbarRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/settings/landing-page': {
      id: '/_auth/settings/landing-page'
      path: '/settings/landing-page'
      fullPath: '/settings/landing-page'
      preLoaderRoute: typeof AuthSettingsLandingPageRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/inquiries/$id': {
      id: '/_auth/inquiries/$id'
      path: '/inquiries/$id'
      fullPath: '/inquiries/$id'
      preLoaderRoute: typeof AuthInquiriesIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/destinations/create': {
      id: '/_auth/destinations/create'
      path: '/destinations/create'
      fullPath: '/destinations/create'
      preLoaderRoute: typeof AuthDestinationsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departures/create': {
      id: '/_auth/departures/create'
      path: '/departures/create'
      fullPath: '/departures/create'
      preLoaderRoute: typeof AuthDeparturesCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/bookings/$id': {
      id: '/_auth/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthBookingsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/blogs/create': {
      id: '/_auth/blogs/create'
      path: '/blogs/create'
      fullPath: '/blogs/create'
      preLoaderRoute: typeof AuthBlogsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/authors/create': {
      id: '/_auth/authors/create'
      path: '/authors/create'
      fullPath: '/authors/create'
      preLoaderRoute: typeof AuthAuthorsCreateRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/tags/edit/$id': {
      id: '/_auth/tags/edit/$id'
      path: '/tags/edit/$id'
      fullPath: '/tags/edit/$id'
      preLoaderRoute: typeof AuthTagsEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/destinations/edit/$id': {
      id: '/_auth/destinations/edit/$id'
      path: '/destinations/edit/$id'
      fullPath: '/destinations/edit/$id'
      preLoaderRoute: typeof AuthDestinationsEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/departures/edit/$id': {
      id: '/_auth/departures/edit/$id'
      path: '/departures/edit/$id'
      fullPath: '/departures/edit/$id'
      preLoaderRoute: typeof AuthDeparturesEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/blogs/edit/$id': {
      id: '/_auth/blogs/edit/$id'
      path: '/blogs/edit/$id'
      fullPath: '/blogs/edit/$id'
      preLoaderRoute: typeof AuthBlogsEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/authors/edit/$id': {
      id: '/_auth/authors/edit/$id'
      path: '/authors/edit/$id'
      fullPath: '/authors/edit/$id'
      preLoaderRoute: typeof AuthAuthorsEditIdRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthProfileRoute: typeof AuthProfileRoute
  AuthAuthorsCreateRoute: typeof AuthAuthorsCreateRoute
  AuthBlogsCreateRoute: typeof AuthBlogsCreateRoute
  AuthBookingsIdRoute: typeof AuthBookingsIdRoute
  AuthDeparturesCreateRoute: typeof AuthDeparturesCreateRoute
  AuthDestinationsCreateRoute: typeof AuthDestinationsCreateRoute
  AuthInquiriesIdRoute: typeof AuthInquiriesIdRoute
  AuthSettingsLandingPageRoute: typeof AuthSettingsLandingPageRoute
  AuthSettingsNavbarRoute: typeof AuthSettingsNavbarRoute
  AuthTagsCreateRoute: typeof AuthTagsCreateRoute
  AuthAuthorsIndexRoute: typeof AuthAuthorsIndexRoute
  AuthBlogsIndexRoute: typeof AuthBlogsIndexRoute
  AuthBookingsIndexRoute: typeof AuthBookingsIndexRoute
  AuthDashboardIndexRoute: typeof AuthDashboardIndexRoute
  AuthDeparturesIndexRoute: typeof AuthDeparturesIndexRoute
  AuthDestinationsIndexRoute: typeof AuthDestinationsIndexRoute
  AuthInquiriesIndexRoute: typeof AuthInquiriesIndexRoute
  AuthMediaIndexRoute: typeof AuthMediaIndexRoute
  AuthNewsletterIndexRoute: typeof AuthNewsletterIndexRoute
  AuthReviewsIndexRoute: typeof AuthReviewsIndexRoute
  AuthTagsIndexRoute: typeof AuthTagsIndexRoute
  AuthUsersIndexRoute: typeof AuthUsersIndexRoute
  AuthAuthorsEditIdRoute: typeof AuthAuthorsEditIdRoute
  AuthBlogsEditIdRoute: typeof AuthBlogsEditIdRoute
  AuthDeparturesEditIdRoute: typeof AuthDeparturesEditIdRoute
  AuthDestinationsEditIdRoute: typeof AuthDestinationsEditIdRoute
  AuthTagsEditIdRoute: typeof AuthTagsEditIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthProfileRoute: AuthProfileRoute,
  AuthAuthorsCreateRoute: AuthAuthorsCreateRoute,
  AuthBlogsCreateRoute: AuthBlogsCreateRoute,
  AuthBookingsIdRoute: AuthBookingsIdRoute,
  AuthDeparturesCreateRoute: AuthDeparturesCreateRoute,
  AuthDestinationsCreateRoute: AuthDestinationsCreateRoute,
  AuthInquiriesIdRoute: AuthInquiriesIdRoute,
  AuthSettingsLandingPageRoute: AuthSettingsLandingPageRoute,
  AuthSettingsNavbarRoute: AuthSettingsNavbarRoute,
  AuthTagsCreateRoute: AuthTagsCreateRoute,
  AuthAuthorsIndexRoute: AuthAuthorsIndexRoute,
  AuthBlogsIndexRoute: AuthBlogsIndexRoute,
  AuthBookingsIndexRoute: AuthBookingsIndexRoute,
  AuthDashboardIndexRoute: AuthDashboardIndexRoute,
  AuthDeparturesIndexRoute: AuthDeparturesIndexRoute,
  AuthDestinationsIndexRoute: AuthDestinationsIndexRoute,
  AuthInquiriesIndexRoute: AuthInquiriesIndexRoute,
  AuthMediaIndexRoute: AuthMediaIndexRoute,
  AuthNewsletterIndexRoute: AuthNewsletterIndexRoute,
  AuthReviewsIndexRoute: AuthReviewsIndexRoute,
  AuthTagsIndexRoute: AuthTagsIndexRoute,
  AuthUsersIndexRoute: AuthUsersIndexRoute,
  AuthAuthorsEditIdRoute: AuthAuthorsEditIdRoute,
  AuthBlogsEditIdRoute: AuthBlogsEditIdRoute,
  AuthDeparturesEditIdRoute: AuthDeparturesEditIdRoute,
  AuthDestinationsEditIdRoute: AuthDestinationsEditIdRoute,
  AuthTagsEditIdRoute: AuthTagsEditIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
