packages:
  # Main server and Admin Panels
  - apps/*
  # Shared UI components and utilities
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  vite: 'npm:rolldown-vite@7.1.20'
