packages:
  - apps/*
  - packages/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - argon2
  - core-js-pure
  - esbuild
  - prisma
  - sharp
  - unrs-resolver

overrides:
  tmp@<=0.2.3: '>=0.2.4'
